add UpdateVersion

diff --git a/genIpa b/genIpa
--- a/genIpa
+++ b/genIpa
@@ -1,41 +1,115 @@
 # !/us/sh
 
-set -e
 
-if [[ "${#@}" = "x" ]];then
-    echo -e "usage: $0 -[DRKEU] [-I [bundle_identify]]\n
--D|--Debug
--R|--Release
--E|--ExportIOSProj
--U|--UploadIpa
--I|--Identify
+function ResetExitOnErr()
+{
+    set -e
+}
+function ResetDebug()
+{
+    set -x
+}
+
+if [[ "${#@}" = "0" ]];then
+    echo -e "usage: $0 [-DRGKEU] [-I [bundle_identifier]]
+    -D|--Debug              Debug build
+    -R|--Release            Release build
+    --IncrBuildNo           Increase build nomber
+    --IncrMajorVersion      Increase major version
+    --IncrMinorVersion      Increase minor version
+    --IncrPatchVersion      Increase patch version
+    -A|--XcodeArchive       Xcode archive
+    -E|--ExportIOSProj      Export iOS project
+    -I|--Identify bundleId  iOS project bundle identifier
+    -K|--KillUnity          Kill Unity process
+    -U|--UploadIpa          Upload ipa to itunesconnect.apple.com for testflight
 "
 fi
 
-temp=$(getopt -o DRKEUI: --long Debug,Release,Kill,ExportIOSProj,UploadIpa,Identify: -- "$@")
+function SetColor()
+{
+    set +x
+    Reset='\033[00m'
+    Red='\033[01;31m'
+    Green='\033[01;32m'
+    Yellow='\033[01;33m'
+    Purple='\033[01;35m'
+    Cyan='\033[01;36m'
+    White='\033[01;37m'
+    Bold='\033[1m'
+    Underline='\033[4m'
+    ResetDebug
+}
+
+if [[ "${JENKINS_HOME}x" = "x" ]];then
+    ResetDebug
+    SetColor
+    echo="echo -e"
+else
+    echo="echo"
+fi
+
+if [[ ! -d "Assets" ]]; then
+   ${echo} "${Red}Error: Not an Unity project dir${Reset}" 
+   ${echo} "${Yellow}Place run genIpa in an Unity project WORKSPACE with an \"Assets\"${Reset}"
+   exit 1
+fi
+
+XcodeArchive="false"
+configuration=${configuration-"Release"} 
+ExportIOSProj=${ExportIOSProj-"false"} 
+UploadIpa=${UploadIpa-"false"}
+KillUnity="false"
+Identify=${Identify-"com.bilibili.a3"}
+
+NewBundleVersion="1.0.0"
+NewbuildNumber="1"
+
+IncrBuildNo="false"
+IncrMajorVersion="false"
+IncrMinorVersion="false"
+IncrPatchVersion="false"
+
+temp=$(getopt -o DRKEUI:A --long XcodeArchive,Debug,Release,KillUnity,ExportIOSProj,UploadIpa,Identify:,\
+IncrBuildNo,IncrMajorVersion,IncrMinorVersion,IncrPatchVersion -- "$@")
 if [ $? != 0  ] ; then 
     echo "terminating..." >&2 
     exit 1 
 fi
 eval set -- "$temp"
 
-configuration=${configuration-"Release"} 
-ExportIOSProj=${ExportIOSProj-"false"} 
-UploadIpa=${UploadIpa-"false"}
-KillUnity="false"
-Identify=${Identify-"com.bilibili.a3"}
 while true;do
     case "$1" in
+    -A|--XcodeArchive)
+        XcodeArchive="true";
+        shift
+    ;;
     -D|--Debug) 
         configuration="Debug"; 
         shift
     ;;
-    -K|--Kill)
+    -R|--Release) 
+        configuration="Release"; 
+        shift
+    ;;
+    -K|--KillUnity)
         KillUnity="true";
         shift
     ;;
-    -R|--Release) 
-        configuration="Release"; 
+    --IncrBuildNo) 
+        IncrBuildNo="true"; 
+        shift
+    ;;
+    --IncrMajorVersion) 
+        IncrMajorVersion="true"; 
+        shift
+    ;;
+    --IncrMinorVersion) 
+        IncrMinorVersion="true"; 
+        shift
+    ;;
+    --IncrPatchVersion) 
+        IncrPatchVersion="true"; 
         shift
     ;;
     -E|--ExportIOSProj) 
@@ -68,55 +142,50 @@ UploadIpa=${UploadIpa}
 Identify=${Identify}
 "
 
-function SetColor()
-{
-    Reset='\033[00m'
-    Red='\033[01;31m'
-    Green='\033[01;32m'
-    Yellow='\033[01;33m'
-    Purple='\033[01;35m'
-    Cyan='\033[01;36m'
-    White='\033[01;37m'
-    Bold='\033[1m'
-    Underline='\033[4m'
-}
-
-if [[ "${JENKINS_HOME}x" = "x" ]];then
-    set -x
-    SetColor
-    echo="echo -e"
-else
-    echo="echo"
+GitSvn="false"
+set +e
+git svn info > /dev/null
+if [[ "$?" = "0" ]];then
+    GitSvn="true"
 fi
-
-if [[ ! -d "Assets" ]]; then
-   ${echo} "${Red}Not an Unity project dir${Reset}" 
-   ${echo} "${Yellow}Place run in an Unity project dir with an \"Assets\"${Reset}"
-   exit 1
-fi
+ResetExitOnErr
 
 uname="$(uname)"
-if [[ "${uname:1:6}" = "Darwin" ]];then
+if [[ "${uname:0:6}" = "Darwin" ]];then
     Unity="Unity"
+    sed="gsed"
 else
     Unity="Unity"
 fi
 
 ${echo} "${Green}Unity-iPhone package tool${Reset} >"
 
-basepath=$(cd `dirname .`;pwd)
+BasePath=$(cd `dirname .`;pwd)
+WORKSPACE="${WORKSPACE-${BasePath}}"
+IosProjDir="ios.proj"
 
-WORKSPACE="${WORKSPACE-${basepath}}"
-
-iosProjDir="ios.proj"
-
+SchemeName="Unity-iPhone"
 ArchiveName="game.$(date "+%Y%m%d-%H%M%S")"
-
 archivePath="${WORKSPACE}/ios.build/${ArchiveName}.xcarchive"
 exportPath="${WORKSPACE}/ios.build"
 exportOptionsPlist="${WORKSPACE}/exportOptionsPlist.plist"
-schemeName="Unity-iPhone"
 
+function DoCommit()
+{
+    file="$1"
+    msg="$2"
+    if [[ "${GitSvn}x" = "truex" ]];then
+        git add "${file}"
+        git commit -m "${msg}"
+        stashmsg=$(git stash)
+        git svn dcommit
+        if [[ "${stashmsg:0:5}" = "Saved" ]];then
+           git stash pop 
+        fi
+    else
+        svn commit -m "${msg}" "${file}"
+    fi
+}
 
 function DoExportIOSProj()
 {
@@ -125,7 +194,7 @@ function DoExportIOSProj()
         ${echo} "kill all unity"
         killall Unity
     fi
-    set -e
+    ResetExitOnErr
 
     mkdir -p "log"
     ${echo} "Export IOS Proj ..."
@@ -133,46 +202,71 @@ function DoExportIOSProj()
         -quit \
         -batchmode \
         -executeMethod "BuildScript.ExportIOSProj" \
-        -logFile "/dev/stdout" | tee "log/unity-$(date "+%Y%m%d-%H%M%S").log"
+        -logFile "/dev/stdout" | \
+        tee "log/unity-$(date "+%Y%m%d-%H%M%S").log"
 
-    #svn ci -m "auto upodate buildNumber" "${WORKSPACE}/ProjectSettings/ProjectSettings.asset"
+    DoCommit "${WORKSPACE}/ProjectSettings/ProjectSettings.asset" "auto upodate buildNumber"
 
     ${echo} "Export IOS Proj done $?"
 }
 
 function DoFixXcodeConfig()
 {
-    local infoplist="$1"
-    VersionString=$(${sed} -n '/CFBundleShortVersionString/{n;s#>\(.*\)<#\1#p}' "${infoplist}")
+    local projectSettingAsset="$1"
+    VersionString=$(${sed} -n '/CFBundleShortVersionString/{n;s#>\(.*\)<#\1#p}' "${projectSettingAsset}")
 }
 
-function DoIncrBuildNum()
+function DoUpdateVersion()
 {
-     ${echo} "updatting Info.plist ..."
-    local infoplist="Info.plist"
+    ${echo} "updatting ProjectSettings.asset ..."
+    local projectSettingAsset="ProjectSettings/ProjectSettings.asset"
     
     ## bundle identifier
-    #${sed} -e '/CFBundleIdentifier/{n;s#>.*<#>'${ACT_PACKAGE_NAME}'<#g}' -i "${infoplist}"
-    
+    #${sed} -e '/CFBundleIdentifier/{n;s#>.*<#>'${ACT_PACKAGE_NAME}'<#g}' -i "${projectSettingAsset}"
+ 
     ## app name
-    # ${sed} -e '/CFBundleDisplayName/{n;s#>.*<#>'${ACT_APP_NAME}'<#g}' -i "${infoplist}"
-    
-    local buildVersion=$(${sed} -n '/CFBundleVersion/{n;s#.*>\(.*\)<.*#\1#p}' "${infoplist}" | cut -d '.' -f4)
-    buildVersion=${buildVersion-'0'}
-    local newbuildVersion=$((buildVersion+1))
-    ${echo} "${buildVersion} => ${newbuildVersion}"
-    #${sed} -e '/CFBundleVersion/{n;s#>.*<#>'"${GEN_VERSION}.${buildVersion}"'<#g}' -i "${infoplist}"
-    #${sed} -e '/CFBundleShortVersionString/{n;s#>.*<#>'${GEN_VERSION}'<#g}' -i "${infoplist}"
+    # ${sed} -e '/CFBundleDisplayName/{n;s#>.*<#>'${ACT_APP_NAME}'<#g}' -i "${projectSettingAsset}"
 
+    # bundle Version
+    local bundleVersion=$(${sed} -n '/bundleVersion/{s#^\s*.*:\s*##p}' "${projectSettingAsset}")
+    bundleVersion=${bundleVersion:-1.0.0}
+    local major=${bundleVersion/\.*}; major=${makor:-0}
+    local minor=${bundleVersion%\.*}; minor=${minor/*\.}; minor=${minor:-0}
+    local patch=${bundleVersion/*\.}; patch=${patch:-0}
+    if [[ "${IncrMajorVersion}x" = "truex" ]];then
+        major=$((major+1))
+        minor=0
+        patch=0
+    elif [[ "${IncrMinorVersion}x" = "truex" ]];then
+        minor=$((minor+1))
+        patch=0
+    elif [[ "${IncrPatchVersion}x" = "truex" ]];then
+        patch=$((patch+1))
+    fi
+    NewBundleVersion="${major}.${minor}.${patch}"
+    ${sed} -e '/bundleVersion/{s#\(:\s*\).*#\1'"${NewBundleVersion}"'#}' -i "${projectSettingAsset}"
+    ${echo} "bundleVersion: ${bundleVersion} => ${NewBundleVersion}"
+    
+    # buildNumber
+    local buildNumber=$(${sed} -n '/buildNumber/{n;s#^\s*.*:\s*##p}' "${projectSettingAsset}")
+    buildNumber=${buildNumber-'0'}
+    NewbuildNumber=${buildNumber}
+    if [[ "${IncrBuildNo}x" = "truex" ]];then
+        NewbuildNumber=$((buildNumber+1))
+        ${sed} -e '/buildNumber/{n;s#\(:\s*\).*#\1'"${NewbuildNumber}"'#}' -i "${projectSettingAsset}"
+    fi
+
+    ${echo} "buildNumber: ${buildNumber} => ${NewbuildNumber}"
 }
 
 function DoXcodeArchive()
 {
     ${echo} "archive ..."
+    pushd "${IosProjDir}"
     security unlock-keychain -p "a3@bilibili"  "/Users/a3/Library/Keychains/login.keychain"
 
     local OTHER_LDFLAGS="-ObjC -lresolv -weak_framework CoreMotion -weak-lSystem -Wl -undefined dynamic_lookup"
-    xcodebuild -scheme "${schemeName}" \
+    xcodebuild -scheme "${SchemeName}" \
         -configuration "${configuration}" \
         archive -archivePath "${archivePath}" \
         -allowProvisioningUpdates \
@@ -183,7 +277,9 @@ function DoXcodeArchive()
         ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES="YES" \
         ENABLE_BITCODE="NO" \
         DEVELOPMENT_TEAM="UL9WJVVZ42"
+    echo "${archivePath}" > .lastArchivePath
     
+    popd
     ${echo} "archive done $?"
 }
 
@@ -191,50 +287,52 @@ function DoXcodeArchive()
 function DoExportIpa()
 {
     ${echo} "export ipa ..."
+    pushd "${IosProjDir}"
 
+    local lastArchivePath="$(cat .lastArchivePath)"
     xcodebuild -exportArchive \
         -exportPath "${exportPath}" \
-        -archivePath "${archivePath}" \
+        -archivePath "${lastArchivePath}" \
         -exportOptionsPlist "${exportOptionsPlist}" 
     
     local ipa="${exportPath}/${ArchiveName}.ipa"
-    mv "${exportPath}/${schemeName}.ipa" "${ipa}"
+    mv "${exportPath}/${SchemeName}.ipa" "${ipa}"
 
+    popd
     ${echo} "export ipa done $?"
 }
 
 
 function DoUploadIpa()
 {
-    ${echo} "upload ipa for testflight ..."
+    ${echo} "upload ipa to itunesconnect for testflight ..."
+    pushd "${IosProjDir}"
 
     local altool="altool"
     local ipa="${exportPath}/${ArchiveName}.ipa"
     ${altool} --upload-app -f "${ipa}" -u "${appleaccount}" -p "${applepsword}"
     
-    ${echo} "upload ipa for testflight done $?"
+    popd
+    ${echo} "upload ipa to itunesconnect for testflight done $?"
 }
 
 ######################### main ######################### 
 
 # sleep 2
 
+DoUpdateVersion
+
 if [[  "${ExportIOSProj}x" = "truex" ]];then
     DoExportIOSProj
 fi
 
+if [[ "${XcodeArchive}x" = "truex" ]];then
+    DoXcodeArchive
+fi
 
 if [[ "${UploadIpa}x" = "truex" ]];then
-
-    pushd "${iosProjDir}"
-
-    DoXcodeArchive
-
     DoExportIpa
-
     DoUploadIpa
-
-    popd
 fi
 
 
